#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate Rust font-metrics data from the Python subset-font metrics modules.

The Python client ships generated `metrics.py` modules (produced by
`scripts/prepare_font.py` from the subset TTFs). Rather than re-derive the same
data with a Rust font parser -- risking a subtle divergence in glyph widths or
the /W array -- this reads those committed modules and emits byte-faithful Rust
`static` data. The embedded TTF is the exact same file, so the reader and the
rendered PDF stay identical to the source of truth.

Run from the repo root:
    python/.venv/bin/python \\
        rust/crates/revenant-core/src/appearance/font_data/generate_font_metrics.py
"""

from __future__ import annotations

import importlib
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent

# Rust module name -> (python metrics module, PDF BaseFont, subset TTF file).
FONTS = {
    "noto_sans": (
        "revenant.core.appearance.font_data.noto_sans.metrics",
        "NotoSans",
        "NotoSans-Subset.ttf",
    ),
    "ghea_mariam": (
        "revenant.core.appearance.font_data.ghea_mariam.metrics",
        "GHEAMariam",
        "GHEAMariam-Subset.ttf",
    ),
    "ghea_grapalat": (
        "revenant.core.appearance.font_data.ghea_grapalat.metrics",
        "GHEAGrapalat",
        "GHEAGrapalat-Subset.ttf",
    ),
}

TUPLES_PER_LINE = 8


def rust_str(s: str) -> str:
    """Emit a valid Rust double-quoted string literal preserving exact bytes."""
    out = ['"']
    for ch in s:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif code < 0x20:
            out.append(f"\\u{{{code:x}}}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def emit_pairs(name: str, elem_type: str, pairs: list[tuple[int, int]]) -> str:
    """Emit a `static NAME: &[(A, B)] = &[ ... ];` block, packed per line."""
    # rustfmt would explode the packed table to one tuple per line; keep it dense.
    lines = ["#[rustfmt::skip]", f"static {name}: &[{elem_type}] = &["]
    for i in range(0, len(pairs), TUPLES_PER_LINE):
        chunk = pairs[i : i + TUPLES_PER_LINE]
        rendered = ", ".join(f"({k}, {v})" for k, v in chunk)
        lines.append(f"    {rendered},")
    lines.append("];")
    return "\n".join(lines)


def generate(rust_name: str, module_path: str, basefont: str, ttf_file: str) -> None:
    m = importlib.import_module(module_path)

    cmap = sorted((int(k), int(v)) for k, v in m.CMAP.items())
    widths = sorted((int(k), int(v)) for k, v in m.WIDTHS.items())

    for cp, gid in cmap:
        if not 0 <= cp <= 0xFFFF_FFFF or not 0 <= gid <= 0xFFFF:
            raise ValueError(f"{rust_name}: cmap entry out of range: {cp}->{gid}")
    for gid, adv in widths:
        if not 0 <= gid <= 0xFFFF or not 0 <= adv <= 0xFFFF:
            raise ValueError(f"{rust_name}: width entry out of range: {gid}->{adv}")

    bbox = tuple(int(v) for v in m.BBOX)

    body = f"""// SPDX-License-Identifier: Apache-2.0
// @generated by generate_font_metrics.py from {module_path} -- do not edit.
//! `{basefont}` subset metrics (glyph coverage, advance widths, embedded TTF).
#![allow(clippy::unreadable_literal)]

use crate::appearance::fonts::Font;

/// The {basefont} font: static metrics plus the embedded subset TTF.
pub(crate) static FONT: Font = Font {{
    name: {rust_str(basefont)},
    units_per_em: {int(m.UNITS_PER_EM)},
    ascent: {int(m.ASCENT)},
    descent: {int(m.DESCENT)},
    cap_height: {int(m.CAP_HEIGHT)},
    bbox: ({bbox[0]}, {bbox[1]}, {bbox[2]}, {bbox[3]}),
    stem_v: {int(m.STEM_V)},
    italic_angle: {int(m.ITALIC_ANGLE)},
    default_width: {int(m.DEFAULT_WIDTH)},
    cmap: CMAP,
    widths: WIDTHS,
    cid_widths_str: {rust_str(m.CID_WIDTHS_STR)},
    tounicode_cmap: {rust_str(m.TOUNICODE_CMAP)},
    ttf: include_bytes!("ttf/{ttf_file}"),
}};

// Unicode codepoint -> glyph ID, sorted by codepoint for binary search.
{emit_pairs("CMAP", "(u32, u16)", cmap)}

// Glyph ID -> advance width (font units), sorted by glyph ID.
{emit_pairs("WIDTHS", "(u16, u16)", widths)}
"""

    out_path = OUT_DIR / f"{rust_name}.rs"
    out_path.write_text(body, encoding="utf-8")
    print(f"wrote {out_path.name} ({len(cmap)} cmap, {len(widths)} widths)")


def main() -> None:
    for rust_name, (module_path, basefont, ttf_file) in FONTS.items():
        generate(rust_name, module_path, basefont, ttf_file)


if __name__ == "__main__":
    main()
